//tratando erros

try {

console.log(nome);

} catch (err)  {
    
    console.log("houve o seguinte erro", `"${err}"`)

} 

console.log("Boa noite, apesar do erro acima")